spring.application.name=sistemaAcademicoDeMatriculas
spring.datasource.url=jdbc:mysql://localhost:3306/sistema_academico_de_matriculas?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=123
# --- Configuracoes do JPA/Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# --- Configuracoles do Flyway ---
spring.flyway.locations=classpath:db/migration
# Desabilita o cache de segundo nível do Hibernate
spring.jpa.properties.hibernate.cache.use_second_level_cache=false
# Desabilita o cache de queries, que também pode guardar resultados antigos
spring.jpa.properties.hibernate.cache.use_query_cache=false
